[package]
name = "rkd"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
anyhow = "1.0.98"
pbkdf2 = { version = "0.12", features = ["simple"] }
sha2 = "0.10.9"
rand = "0.9.1"
hex = "0.4.3"
scrypt = "0.11.0"
argon2 = "0.5.2"
base64 = "0.22.1"
subtle = "2.6.1"
